# Generated by Django 3.1 on 2020-08-13 11:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_cat', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=250)),
                ('question_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choice', models.CharField(max_length=250)),
                ('currect_ans', models.CharField(choices=[('1', 'False'), ('2', 'Currect')], max_length=1, verbose_name='Choice Currect Answer')),
                ('question_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.questions', verbose_name='Questions Category')),
            ],
        ),
    ]
